### ISSUE TITLE
Appears to require jwst_backgrounds

### ISSUE THREAD

**Issue by eas342** [JarronL/pynrc#21]
* pyNRC version: 0.6.5
* Python version: 2.7
* Operating System:10.10.5

### Description

Trying to install without jwst_backgrounds. Sounds like it's supposed to work without jwst_backgrounds so installer doesn't require it.
Maybe put it back in as a requirement?

### What I Did

MacBook-Pro:pynrc everettschlawin$ pip install .
Processing /Users/everettschlawin/outside_progs/pynrc/pynrc
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mf/jzbqy3z14sx1s6qkkkpgs4rc0000gn/T/pip-req-build-EVX43M/setup.py", line 18, in <module>
        from pynrc.version import __version__
      File "pynrc/__init__.py", line 74, in <module>
        from .nrc_utils import (read_filter, pix_noise, nrc_header, bp_2mass, bp_wise, \
      File "pynrc/nrc_utils.py", line 41, in <module>
        if not on_rtd: from jwst_backgrounds import jbt
    ImportError: No module named jwst_backgrounds
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/jzbqy3z14sx1s6qkkkpgs4rc0000gn/T/pip-req-build-EVX43M/

**Comment by JarronL** [comment]
The pynrc install docs [here](https://pynrc.readthedocs.io/en/latest/installation.html) and [here](https://pynrc.readthedocs.io/en/latest/install_clean.html) both explicitly mention jwst_backgrounds as a requirement. Can you point me to where this is ambiguous?
