### ISSUE TITLE
Recursive calling of source script when using pynrc.NIRCam()

### ISSUE THREAD

**Issue by AarynnCarter** [JarronL/pynrc#35]
* pyNRC version: Commit b4744da679016c7a2d8f362e728dabcf12a92c16
* Python version: 3.8.0
* Operating System: macOS Mojave 10.14.4

### Description

Attempting to call the pynrc.NIRCam() function

### What I Did

Here is my input code:

```
import pynrc

print('Hello')
nrc = pynrc.NIRCam(filter='F356W', pupil='CIRCLYOT', mask='MASK335R', wind_mode='WINDOW', xpix=320, ypix=320)
```

I've pasted the full output below, I end up in a recursive loop.

```
[     pynrc:INFO]   jwst_backgrounds is not installed and will not be used for bg estimates.
Hello
[     pynrc:INFO]   jwst_backgrounds is not installed and will not be used for bg estimates.
Hello
[     pynrc:INFO]   jwst_backgrounds is not installed and will not be used for bg estimates.
Hello
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/acarter/Documents/DIRECT_IMAGING/JWST_SIM/CODE/testing_pynrc.py", line 11, in <module>
    nrc = pynrc.NIRCam(filter='F356W', pupil='CIRCLYOT', mask='MASK335R', wind_mode='WINDOW', xpix=320, ypix=320)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/site-packages/pynrc/pynrc_core.py", line 497, in __init__
    self.update_psf_coeff(**kwargs)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/site-packages/pynrc/pynrc_core.py", line 1256, in update_psf_coeff
    self._psf_coeff = psf_coeff(self.bandpass, self.pupil, self.mask, self.module, 
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/site-packages/pynrc/nrc_utils.py", line 1307, in psf_coeff
    pool = mp.Pool(nproc)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/acarter/Documents/DIRECT_IMAGING/JWST_SIM/CODE/testing_pynrc.py", line 11, in <module>
    nrc = pynrc.NIRCam(filter='F356W', pupil='CIRCLYOT', mask='MASK335R', wind_mode='WINDOW', xpix=320, ypix=320)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/site-packages/pynrc/pynrc_core.py", line 497, in __init__
    self.update_psf_coeff(**kwargs)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/site-packages/pynrc/pynrc_core.py", line 1256, in update_psf_coeff
    self._psf_coeff = psf_coeff(self.bandpass, self.pupil, self.mask, self.module, 
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/site-packages/pynrc/nrc_utils.py", line 1307, in psf_coeff
    pool = mp.Pool(nproc)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/acarter/anaconda/envs/pancake/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
[     pynrc:INFO]   jwst_backgrounds is not installed and will not be used for bg estimates.
Hello
```
Which then repeats ad nauseum. As you can see it keeps printing 'Hello' even though this occurs prior to the call to pynrc.NIRCam(). 

I've remedied the fix for now through adjusting code prior to line 1358 in the nrc_utils.py file to instead be:

```
if __name__ == '__main__':
    freeze_support()
    hdu_arr = pool.map(_wrap_coeff_for_mp, worker_arguments)
```

Although I'm not sure how long term this solution will be, it might be better to determine exactly why the pynrc.NIRCam() function is starting my initial script over and over again (hence why I haven't put in a pull request).

**Comment by JarronL** [comment]
This is a really odd behavior that I haven't seen before. According to the `multiprocessing` [documentation](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.freeze_support), `freeze_support` should only be applicable for producing Windows executables.

> Calling freeze_support() has no effect when invoked on any operating system other than Windows.

Does this happen when calling `pynrc.NIRCam()` from the ipython command line or just when running your code from a .py script file?

**Comment by JarronL** [comment]
Can you also check on a different version of Python, such as v3.6? I haven't yet tried v3.8.

**Comment by AarynnCarter** [comment]
I wasn't aware freeze_support() was only applicable for Windows executables, the if statement must have made the difference.

All that said, I'm not really sure what to say here. I've been rerunning this simple script again in a variety of situations:

- iPython or not
- python 3.6 / 3.8
- commit b4744da vs the latest commit
- with the lines I added or not

and I can't repeat the issue... I'm at a bit of a loss for words as nothing else has changed in the mean time, I'm pretty sure I'm running it in the same terminal window as well. I guess it's good that the issue is no longer there, however it's a bit of a shame that I can't figure out what was causing it (be it the pyNRC package or my system). Unless this crops up again I think it'll have to be left as one of life's mysteries.

**Comment by JarronL** [comment]
Ok, so, just to clarify, everything works fine now with the unmodified code (`freeze_support` excluded)?

For purposes of testing, make sure to delete the relevant PSF coefficient file in your pynrc_data directory at `pynrc_data/psf_coeff/`, otherwise it won't call the multiprocessing function since it will find and use the PSF info previously saved to disk. Or you can set the keyword `force=True` in order to force it to re-calculate the PSF.

**Comment by JarronL** [comment]
Closing since this hasn't reared its head in a while...
